### ISSUE TITLE
object key naming should not contain '#'

### ISSUE THREAD

**Issue by onichandame** [node-fetch/fetch-blob#115]
### Problem

in [a source file](https://github.com/node-fetch/fetch-blob/blob/main/index.js#L48), some keys of a class have `#` in its name. This may be ok in most situations(I haven't verified tho), but it breaks when using webpack. The error message being:

```text
Module parse failed: Unexpected character '#' (48:1)
```

**Comment by jimmywarting** [comment]
We only target v12.17 and above now
Private fields got supported in node v12.0.0

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

try updating webpack?

**Comment by onichandame** [comment]
fetch-blob has been removed from my dependency tree so the issue is irrelevant for me atm. Even if I will encounter the issue again I guess I should tweak webpack to parse the private fields.
