### ISSUE TITLE
fileFromSync just part of a file

### ISSUE THREAD

**Issue by leopucci** [node-fetch/fetch-blob#136]
Hey there! Nice work!

I am trying to append on a form just part of a file, 
Is there some way that I could append fom 0 to 1024 bytes on fileFromSync(0,1024,/path/to/file)
Thanks
Pucci

**Comment by jimmywarting** [comment]
just do: 
```js
fileFromSync(path).slice(0, 1024).text()
```
it's quite cheap operation do create new chunk, nothing will ever be read into memory by using `fileFromSync` until you actually try to read anything

a Blob/File is more like a references (file handle) that points to a location on the disk from where it can be read from

when you `slice()` then you are creating a new Blob chunk with a different size & offset
