### ISSUE TITLE
work without web-streams-polyfill?

### ISSUE THREAD

**Issue by Pomax** [node-fetch/fetch-blob#141]
The `web-streams-polyfill` dependency is a whopping 7.5MB, would it be possible to determine which parts of it are actually necessary for the current LTS and newer versions of Node, and only require those parts in directly, rather than needing almost 8MB for a 20kb library? =S

**Comment by jghaanstra** [comment]
Unfortunately getting this sorted seems to have come to a full stop. There are already various closed issues on this topic, [one open issue](https://github.com/node-fetch/node-fetch/issues/1217#issuecomment-1239298922) and even a [draft PR](https://github.com/node-fetch/fetch-blob/pull/116) that seems to be going nowhere.

**Comment by Pomax** [comment]
Yeah. I ended up just writing a `fetch.js` that does exactly the bare minimum I need it to do in less than 1000 bytes using the node `http` and `https` modules' request and a Promise,

**Comment by jimmywarting** [comment]
ping @MattiasBuelens how is v4 coming along?

**Comment by Pomax** [comment]
@jimmywarting note that as of Node 18, you no longer need node-fetch, you just get the Fetch API with Node now.

**Comment by Pomax** [comment]
As per the above comment, this issue is now moot. Just use Node.

**Comment by jghaanstra** [comment]
> Yeah. I ended up just writing a `fetch.js` that does exactly the bare minimum I need it to do in less than 1000 bytes using the node `http` and `https` modules' request method wrapped in a Promise so that it acts exactly the same as the Fetch API. And now my project/node_modules dir is 8mb lighter.

Could you share this somewhere. I have given up this ever getting sorted in node-fetch v3 but I'm not quite ready yet to switch to another solution.

**Comment by jimmywarting** [comment]
@jghaanstra read the docs about:
http - https://nodejs.org/dist/latest-v19.x/docs/api/http.html
https - https://nodejs.org/dist/latest-v19.x/docs/api/https.html
fetch - https://nodejs.org/dist/latest-v19.x/docs/api/globals.html#fetch
and blob - https://nodejs.org/dist/latest-v19.x/docs/api/globals.html#class-blob

This is not the place to have this kind of discussion
