### ISSUE TITLE
Release with Typings?

### ISSUE THREAD

**Issue by drewctate** [node-fetch/fetch-blob#35]
I see typings in the current version of the repository, but not when I install from NPM. What is the timeline for a release that includes typings?

**Comment by LinusU** [comment]
@Richienb would it be possible to get a release published to npm? ☺️

**Comment by Richienb** [comment]
@bitinn Can you create a new release of fetch-blob or give me publish perms?

**Comment by LinusU** [comment]
If you need another maintainer I would be happy to step up and help as well! I believe that we already maintain one or two packes together? 😄 (md5-file comes to mind) I also maintain some similar packages `@canvas/image` & `@canvas/image-data` which are Node.js versions of `Image` and `ImageData`...

**Comment by Richienb** [comment]
Sure! We are looking for a bunch of reviewers to help maintain everything in this org, especially node-fetch. I've sent an invite.

**Comment by LinusU** [comment]
Awesome, accepted!

**Comment by bitinn** [comment]
@Richienb same with node-fetch, I have added @xxczaki @jimmywarting to npm owner list.

**Comment by jimmywarting** [comment]
fyi, i see that `slice` is missing in d.ts

**Comment by xxczaki** [comment]
@bitinn Did you add `xxczaki` to npm owner list? Because my npm username is `akepinski` and I don't seem to have the owner permissions :cry:

**Comment by bitinn** [comment]
@jimmywarting cool catch, that's why I added you

@xxczaki it's funny, I added you before I add jimmy, both returns success, but when I query only jimmy's owner permission got added (there is also response caching in the mix).

I am adding your name again, it seems to go through now :)

**Comment by jimmywarting** [comment]
hmm, but if it extends Blob then maybe size, slice and type isn't needed after all...

**Comment by LinusU** [comment]
@jimmywarting yeah, `slice` etc. will be included from here:

https://github.com/microsoft/TypeScript/blob/dbaeed5ad87cf846dddf0d278df3699e9f91cd21/lib/lib.dom.d.ts#L2537-L2544

**Comment by jimmywarting** [comment]
> actually, we should probably remove the duplicates 🤔

was thinking the same

**Comment by LinusU** [comment]
Personally, I think that this approach is the best: https://github.com/node-fetch/fetch-blob/pull/38

**Comment by Richienb** [comment]
@xxczaki Can you create a new release?

**Comment by xxczaki** [comment]
@Richienb Done.

- https://github.com/node-fetch/fetch-blob/releases/tag/v1.0.6
- https://www.npmjs.com/package/fetch-blob/v/1.0.6

**Comment by drewctate** [comment]
Thanks everyone. Super helpful.

**Comment by CyberMew** [comment]
I just tried `npm i --save-dev @types/fetch-blob` as suggested to use `import blobFrom from "fetch-blob/from.js";` instead of `const blobFrom = require("fetch-blob/from.js");` and it didn't find anything.. is this correct?
