### ISSUE TITLE
Checking (null instanceof Blob) throws an exception

### ISSUE THREAD

**Issue by tupelo-schneck** [node-fetch/fetch-blob#58]
Checking `(null instanceof Blob)` throws the exception: `TypeError: Cannot read property 'stream' of null`.

**Comment by octet-stream** [comment]
@tupelo-schneck I believe this issue is resolved since v2.1.2 release.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/7884558/115449548-a3c3b800-a223-11eb-986c-892aa7102a9f.png)


</details>

**Comment by tupelo-schneck** [comment]
I confirm!
