### ISSUE TITLE
v2.1.2 contains breaking changes.

### ISSUE THREAD

**Issue by BlackGlory** [node-fetch/fetch-blob#87]
I don't have a clue about this, all my related test cases failed on 2.1.2.

In addition, v2.1.2 does not have a git tag, and 2.1.1 and 2.1.0 are also very confusing in the commits.

**Comment by octet-stream** [comment]
Hi! I think this may happen because of this: https://github.com/node-fetch/fetch-blob/pull/85
You'll better stick with 2.1.1 until the next version is arrive...

**Comment by octet-stream** [comment]
I mean, this PR should fix the problem

**Comment by jimmywarting** [comment]
Do you know what is failing?
can you figure out what is breaking?

**Comment by BlackGlory** [comment]
Sorry, I don't have time to reply.

I tried the latest commit (https://github.com/node-fetch/fetch-blob/commit/a8fed4e338f58592cdc6f9c1b453b3cea6684d77) and it passed the test,
so I guess #85 fixed the problem. When will the new version be published?
